name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

      - name: Unit tests
        run: go test ./... -count=1 -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests

      - name: Build
        run: go build -o /usr/local/bin/ssh-get-id ./cmd/ssh-get-id/

      - name: Integration tests
        run: |
          bash ./tests/run.sh
          bash ./tests/gh.sh
